// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpYTXLNzOb4dorCe0Jvt2SuBYznzkFjI',
    appId: '1:498505194595:web:fbc7332b13bbb5a94f6c56',
    messagingSenderId: '498505194595',
    projectId: 'remindly-revisionbyte',
    authDomain: 'remindly-revisionbyte.firebaseapp.com',
    storageBucket: 'remindly-revisionbyte.appspot.com',
    measurementId: 'G-C6526HFXMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABeJYxSjkG-j-ZBcSCqhaMcEN1s31TrlU',
    appId: '1:498505194595:android:04cf90ea2a362f034f6c56',
    messagingSenderId: '498505194595',
    projectId: 'remindly-revisionbyte',
    storageBucket: 'remindly-revisionbyte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ajndE3wqcbFjDmYDnGjbuwkaDljlwjA',
    appId: '1:498505194595:ios:ac459461f87e18ec4f6c56',
    messagingSenderId: '498505194595',
    projectId: 'remindly-revisionbyte',
    storageBucket: 'remindly-revisionbyte.appspot.com',
    iosClientId: '498505194595-eh4r7eg6g8g7q76vi4ncvr0b760fp6m0.apps.googleusercontent.com',
    iosBundleId: 'com.remindly.remindly',
  );
}
